# Workflow
# should have the name

name: Hello

# On tells when the workflow run
on:
  workflow_dispatch: 

# Jobs
#should be inside the workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: say hello to everyone
      run: echo "Hello Dosto"

